// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Y9YM5D2skvooVR_EfQWZmX9f5qE_YoI',
    appId: '1:201721663741:web:092cb33d0dc7e221b0ee94',
    messagingSenderId: '201721663741',
    projectId: 'curd-app-8cdbf',
    authDomain: 'curd-app-8cdbf.firebaseapp.com',
    storageBucket: 'curd-app-8cdbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUGVYsAyesaAjWTHpiImprQEJzxPfS0cg',
    appId: '1:201721663741:android:dcd009d458e69486b0ee94',
    messagingSenderId: '201721663741',
    projectId: 'curd-app-8cdbf',
    storageBucket: 'curd-app-8cdbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQlag_YIftVu-2X8v9bxyEF39nWsrw0k',
    appId: '1:201721663741:ios:7c47326de56c00a5b0ee94',
    messagingSenderId: '201721663741',
    projectId: 'curd-app-8cdbf',
    storageBucket: 'curd-app-8cdbf.appspot.com',
    androidClientId: '201721663741-j67spvbmqvf74t1amjq2go7042gjs6fo.apps.googleusercontent.com',
    iosClientId: '201721663741-e4gs0tcg9e2jb6adaqr9rekkptsrcose.apps.googleusercontent.com',
    iosBundleId: 'com.date.colmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQlag_YIftVu-2X8v9bxyEF39nWsrw0k',
    appId: '1:201721663741:ios:3e3fe305c55571d5b0ee94',
    messagingSenderId: '201721663741',
    projectId: 'curd-app-8cdbf',
    storageBucket: 'curd-app-8cdbf.appspot.com',
    androidClientId: '201721663741-j67spvbmqvf74t1amjq2go7042gjs6fo.apps.googleusercontent.com',
    iosClientId: '201721663741-tbrs83rt5mq36ncstneudhlobimtm8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.colmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Y9YM5D2skvooVR_EfQWZmX9f5qE_YoI',
    appId: '1:201721663741:web:e1490dcc50eaf719b0ee94',
    messagingSenderId: '201721663741',
    projectId: 'curd-app-8cdbf',
    authDomain: 'curd-app-8cdbf.firebaseapp.com',
    storageBucket: 'curd-app-8cdbf.appspot.com',
  );

}